#!/bin/bash

BUS=${BUS:-"system"}

SERVICENAMES=( "$@" )
echo "$@"
# for f in "${files[@]}"
for service_name in "${SERVICENAMES[@]}"
do
    
    dbus_paths=$(busctl "--${BUS}" tree  --list "${service_name}")
    tree_exit_code="$?"
    
    if [ "${tree_exit_code}" -eq "1" ]
    then
        echo "Service name ${service_name} not found on this bus."
        continue
    fi

    for dbus_path in ${dbus_paths}
    do
        echo "service name: ${service_name}"
        echo "object path: ${dbus_path}"
        intro_data=$(busctl "--${BUS}" introspect --no-legend "${service_name}" "${dbus_path}")
        
        if [ -n "${intro_data}" ]
        then
            echo "${intro_data}"
        fi
        
        echo
    done
    
    echo
done

#for i in $(busctl tree  --list org.freedesktop.ColorManager); do echo; busctl introspect "$@"^C$i"; done
